dist: xenial
os: linux
language: ruby
cache: bundler
rvm:
- 2.5.1

script: bundle install && bundle exec jekyll build

deploy:
  provider: pages
  # edge: true -> for cleanup
  edge: true 
  # cleanup: false -> dpl v2
  cleanup: false
  token: $LINDAREX_GITHUB_TOKEN
  keep_history: true
  local_dir: ./_site
  target_branch: master
  on:
    branch: sources

branches:
  only:
  - sources
