language: ruby
cache: bundler
rvm:
- 2.5.1

script: bundle install && bundle exec jekyll build

exclude: [vendor]

deploy:
  provider: pages
  cleanup: false
  github_token: $LINDAREX_GITHUB_TOKEN
  keep_history: true
  local-dir: ./_site
  target-branch: master
  on:
    branch: sources

branches:
  only:
  - sources
